apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deadchat.fullname" . }}-data
  labels:
    {{- include "deadchat.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
