apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deadchat.fullname" . }}-secret
  labels:
    {{- include "deadchat.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.backend.jwtSecret | b64enc | quote }}
