apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: deadchat-backend-data
  namespace: deadchat
  labels:
    app: deadchat
    component: backend
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
